### ISSUE TITLE
register.url not functional

### ISSUE THREAD

**Issue by hostalp** [featurehub-io/featurehub#330] opened 2021-04-25 20:46 UTC
The application doesn't add request path and parameter to the registration URL if it's configured via `app-config/application.properties` - `register.url`

**Describe the bug**
- Running via docker compose, using the **all-separate-postgres** variant
- Application is accessed via a NGINX reverse proxy with TLS/SSL offloading configured.
- New users were getting registration URLs beginning with `http://localhost:8085` which aren't usable in the real environment where the actual host name has to be used.
- Based on https://docs.featurehub.io/installation.html#_management_repository we added the `register.url=https://featurehub.localdomain.net` property to `app-config/application.properties`
- Resulting registration URLs match exactly the configured value, e.g. they're always the same and missing the path and parameters (something like `/#/register-url?token=XYZ`).

 Which area does this issue belong to?

* [X] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.
- CentOS Linux release 8.3.2011 x86_64
- Docker version 20.10.6, build 370c289
- docker-compose version 1.29.1, build c34c88b2
- https://github.com/featurehub-io/featurehub-install/releases/tag/release-1.2.1 running with freshly pulled container images

**Additional context**
For reference, the used NGINX reverse proxy config:
```
        location / {
            client_max_body_size 14M;
            proxy_pass http://127.0.0.1:8085;
            proxy_set_header Host $host;

            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
```

**Comment by rvowles** [comment] 2021-04-25 21:31
Oh dear. I'll add a test to replicate this and get a resolution for you.

**Comment by rvowles** [comment] 2021-04-26 00:23
Hi there, the problem is the format you are using, our docs aren't very clear about this. 

the format has to be:

register.url=http://localhost:8085/#/register-url?token=%s

where the %s will be replaced by a token. So following your example, you should set yours to:

register.url=https://featurehub.localdomain.net/#/register-url?token=%s

**Comment by rvowles** [comment] 2021-04-28 05:16
please confirm and i can close this issue, thanks

**Comment by rvowles** [comment] 2021-05-13 20:50
assuming fixed, closing

**Closed by rvowles** 2021-05-13 20:50 UTC
