### ISSUE TITLE
OAuth2 not working with Generic Self-Managed OAuth Provider

### ISSUE THREAD

**Issue by pktsk** [featurehub-io/featurehub#674] opened 2022-01-25 15:04 UTC
**Describe the bug**
We are using feature-hub for our internal use. For the same, we want to allow only organisation employees of mine to login to MR Web. 
We do not have Google, Azure or Github OAuth provider.

**It's not working with our self-managed OAuth service which we wan't to enable in MR Web.**

**Describe the solution you'd like**
Support for self-managed OAuth service in MR Web.

 Which area does this issue belong to?

* FeatureHub Admin Web app

**Screenshots**
- Application props file containing Github, Google and Jio (Self-managed) provider.
<img width="970" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/35165140/151001748-0e6f116c-f867-448f-b230-6ec0eb0adad4.png">

* Don't see any OAuth button for Jio (Self-managed) provider.
<img width="1680" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/35165140/151001883-4a3248c5-fb3c-4045-88f8-b01cacdcf439.png">

**Versions**
 - FeatureHub version [latest]
 - OS: [Mac OS Catalina]
 - Browser [e.g. chrome]

**Comment by rvowles** [comment] 2022-02-03 05:27
This is a duplicate of #673 so closing and keeping that one :-)

**Closed by rvowles** 2022-02-03 05:27 UTC
