### ISSUE TITLE
featurehub-eventsource-sdk (typscript) libraries seem to cause problems in an angular 10 app

### ISSUE THREAD

**Issue by csydvs** [featurehub-io/featurehub#341] opened 2021-04-28 21:52 UTC
**Describe the bug**
Adding featurehub sdk to Angular app produces a bunch of errors, can't serve the app.

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [x] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Clone https://gitlab.com/cdavis3/angular-basic-featurehub, run `npm start`

OR

1. Generate new angular 10 project (`ng new angular-featurehub-app`)
2. Install featurehub-eventsource-sdk (`npm i featurehub-eventsource-sdk`)
3. Modify app.component.ts as shown [here](https://gitlab.com/cdavis3/angular-basic-featurehub/-/blob/master/src/app/app.component.ts) in reference example (but with appropriate url and key)
4. `npm start`
5. See errors in output log of npm start

```
ERROR in ./node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'http' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/eventsource/lib'

ERROR in ./node_modules/featurehub-repository/dist/test_sdk.js
Module not found: Error: Can't resolve 'http' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/featurehub-repository/dist'

ERROR in ./node_modules/featurehub-repository/dist/polling_sdk.js
Module not found: Error: Can't resolve 'http' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/featurehub-repository/dist'

ERROR in ./node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'https' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/eventsource/lib'

ERROR in ./node_modules/featurehub-repository/dist/analytics.js
Module not found: Error: Can't resolve 'https' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/featurehub-repository/dist'

ERROR in ./node_modules/featurehub-repository/dist/test_sdk.js
Module not found: Error: Can't resolve 'https' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/featurehub-repository/dist'

ERROR in ./node_modules/featurehub-repository/dist/polling_sdk.js
Module not found: Error: Can't resolve 'https' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/featurehub-repository/dist'

ERROR in ./node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in '/Users/cdavis/Workspace/angular-basic-featurehub/node_modules/assert-plus'
```

**Expected behavior**
Should be able to spin up ClientContext without dependency issues.

**Desktop (please complete the following information):**
 - OS: iOS (10.15.7)
 - Browser: Chrome
 - Version: Featurehub party server running 1.3.0, Angular 10.2.3, featurehub-eventsource-sdk 2.0.0, Docker version 20.10.5

**Additional context**
The first time I was trying to create a reference example, I created an angular 8 app and compiled just fine, but got different errors in the browser console from the buffer library trying to access global.

It looks like there's a polyfill for eventsource that allows it to be used in a browser context and would fix this, but given that you guys have a working react example, maybe you're already using that? I couldn't figure out how to override the sdk to use that, however, so maybe it's something that can just be hooked up easily with angular. 

Thanks for taking a look!

**Comment by rvowles** [comment] 2021-04-28 21:53
@csydvs is this a dupe of #301 ?

**Comment by csydvs** [comment] 2021-04-28 22:01
Ah, very well could be, and I'm content with marking it that way if you think it is. I had been searching for variations of my specific error text in the issues along with "Angular", and it hadn't shown up because of the difference in behavior, but I wouldn't be surprised if the two issues had the same root cause.

**Comment by rvowles** [comment] 2021-04-29 01:40
Yeah, I think that stack trace is very helpful as the issue is that Webpack is clever enough to drop the code it detects it isn't using, but because the library includes both nodejs and browser code, and detects which context its being run in, Angular is a bit more through in its examination. 

Its a couple of items down on my list, but I need to look at it and get an Angular example into the example repo.

**Comment by rvowles** [comment] 2021-05-08 04:18
The reason behind this is because the libraries mix nodejs + browser support in one library, and Angular simply doesn't like this. I have a working version now with Angular but I have needed to pull the nodejs stuff out into a separate library. We need to discuss this internally how we will repackage, document and communicate this but it should be ready soon.

**Closed** 2021-05-08 22:15 UTC
