### ISSUE TITLE
Cannot save feature changes  

### ISSUE THREAD

**Issue by kasperite** [featurehub-io/featurehub#1125] opened 2024-02-13 20:59 UTC
There is a bug in featurehub admin which happens in a particular sequence. I have attached a screen capture for demoing purpose

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**

1. Open a locked feature
2. Unlock feature
3. change feature value
4. lock feature
5. Click Save
6. See error `An unexpected error occurred`

**Expected behavior**
feature value should be updated and feature should be locked 

**Screenshots**

https://github.com/featurehub-io/featurehub/assets/1487096/72c4970b-8af5-41fa-acbf-7ab3c153e8f3

**Versions**

 - OS: macOS 14 Sonoma
 - Browser:  Brave (latest version)

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**

**Comment by rvowles** [comment] 2024-02-13 21:01
Hey, this is listed here under another ticket: https://github.com/featurehub-io/featurehub/issues/1094

Its more of a UI flow issue - the UI should not let you relock the issue  before you save it, because the data you  are sending to the server is a single change - which is an updated feature value (and that feature value is still locked).

**Comment by IrinaSouth** [comment] 2024-02-13 21:29
Marking as duplicate of #1094 and closing for now.

**Closed by IrinaSouth** 2024-02-13 21:29 UTC
Labels: duplicate
