### ISSUE TITLE
Issue accessing flags/values from the SDK when set the first time

### ISSUE THREAD

**Issue by amr-labib** [featurehub-io/featurehub#544] opened 2021-09-27 23:03 UTC
**Describe the bug**
When a new value or configuration is created and set for the first time, the NodeJS SDK reports it as still unset. When the same value or configuration is changed/set again for the second time, the NodeJS SDK fetches it correctly. Any other changes are reflected correctly. The problem only happens the firs time.

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [*] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. In an existing application connected to FH using NodeJS SDK, create a new feature value or configuration.
2. Set the value or configuration to any desired value only once.
3. Attempt to fetch the value or configuration using the NodeJS SDK.
4. The value or configuration is seen as unset.

**Expected behavior**
The value or configuration should return the set value.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04 and Docker 20.10.7
 - Browser: N/A
 - Version:
     - featurehub/edge:1.4.0 
     - featurehub/dacha:1.4.0
     - featurehub/mr:1.4.0
     - featurehub-javascript-node-sdk:1.0.5

**Additional context**

**Comment by rvowles** [comment] 2021-10-04 18:28
Just to let you know my progress on this, i've been coming up with an example I can easily setup and trace through to see if I can determine where the issue is.  I have created a full project with service account and application but with no features and started listening to it, then added a new feature (which comes through not-set), then set it (and it comes thru), and set it again. So up to  the data coming back from the service it seems OK. I will proceed into the NodeSDK now and trace it further into there, it could be a version change detection issue or a value change detection issue.

**Comment by rvowles** [comment] 2021-10-07 08:19
The other thing is that your Node SDK needs to be at least 1.0.6 if you are using SSE.

**Comment by rvowles** [comment] 2021-10-11 00:52
Much appreciated - it will be good to get this replicated and nailed if you can :-)

**Comment by amr-labib** [comment] 2021-10-11 01:03
@rvowles I upgraded the SDK to 1.0.8 and upgraded FH to 1.4.1 however the problem is still happening on my end. I tested this on our live FH deployment. I will try next to spin up FH locally and extract the relevant parts of our code and test it again. If I can replicate it in this environment, I will share the code with you.

**Comment by IrinaSouth** [comment] 2022-01-10 06:01
@amr-labib hey there, just to confirm, we have found the cause of this issue and it will be fixed in the next version 1.5.4

**Comment by rvowles** [comment] 2022-01-10 07:11
We now have ADK/SDK tests in the repository that are designed to cover this and we found a specific scenario under which it occurs.

**Closed** 2022-01-10 20:44 UTC
