### ISSUE TITLE
New Dacha1 servers should not be able to start up if they are in a bad state

### ISSUE THREAD

**Issue by cspalding** [featurehub-io/featurehub#973] opened 2023-04-05 17:37 UTC
**Describe the bug**
My team has FeatureHub deployed using the [streaming scalable architecture](https://docs.featurehub.io/featurehub/latest/installation.html#_option_2a_streaming_scalable_deployment). We deploy FeatureHub on GKE using v3.0.4 of the Helm Chart.

When our Dacha deployment restarts, new pods frequently enter a 'Ready' state even when they are unhealthy. We consistently see new pods emit the following sequence of log messages on startup:
```
> unable to decode message on environment channel
> cache (<id>) filled, at rest.
```

Following the `cache (<id>) filled ...` message, the pod starts serving tracking and returning 100% 404s. The only way we have been able to resolve these issues is by scaling our Dacha ReplicaSet down to 0 and then scaling it back up to our desired number of servers.

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [x] Other

**To Reproduce**

One way that seems to guarantee this behavior is to restart the NATS statefulset and not let it finish restarting before you restart the Dacha deployment. I believe in that scenario new Dacha servers will come up and mark themselves as 'Ready' without being able to communicate with NATS.

Unfortunately this behavior doesn't happen on _every_ restart of the Dacha deployment, but it does happen frequently.

**Expected behavior**

1. Dacha pods should pass their health and readiness checks until their cache is properly full and the pods are ready to serve traffic
2. If Dacha pods _do_ become ready with a bad cache, requests to that server should return 5xx errors, _not_ 404s so that service maintainers can leverage features like Istio Outlier Detection to stop those pods from serving requests.

**Screenshots**

**Versions**
 - FeatureHub version 1.6.0 (Dacha1)
 - SDK Version: NA
 - OS: I think it's a Linux server? Not 100%
 - Browser: NA

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**

My team is happy to work on fixing this issue if that's okay with the FeatureHub team - we just didn't want to go making code changes in y'all's codebase without sign off from your team so that we can avoid blocked PRs/wasted effort

**Comment by rvowles** [comment] 2023-04-07 20:21
So the Dacha1 protocol is such that a Dacha1 will become ready under two conditions:

(1) When it is told that the number of service accounts it now has in its cache is equal to the number of service accounts that is attached to each service account record, or it is told that there are no service accounts. Each PublishServiceAccount has the details of the service account AND the total number of service accounts. 
(2) The same occurs for environments.

In a k8s cluster, a not-ready Dacha1 will not get traffic routed to it, so there is no issue with what the error response codes are. 

I'm wondering if the issue is actually timed based. Explaining how this worked has made me think of a possible issue.

**Comment by rvowles** [comment] 2023-04-07 21:22
I was checking to see if one dacha filling another dacha after a reset caused the original dacha to publish environment & service account "counts" with the wrong values, but they don't, if one dacha fills another, it resets the total number to what it has in its own cache correctly. Back to sq one.

**Comment by rvowles** [comment] 2023-04-07 21:33
The code base as 3 dacha servers configured as test cases, i ran up two and then shut down the nats server and started the 3rd. The 1st two started complaining about lost connectivity and the 3rd wouldn't come ready. i started the nats server again and they recovered and the 3rd one advertised for its cache (when  the health check was hit) and became ready (with the correct number of environments in the cache).  So I'm at a bit of a  loss.

**Comment by MarcRoser** [comment] 2023-04-21 08:42
Similar issue that may happen after k8s has no resources left (cpu/ram/...) : when k8s is ready again : 
- the features may not be updated correctly anymore (retired ones are still sent, changes are not sent)
- "API KEY does not exist." may happen with valid key (retries works with the same key)
- Everythings seems ok with the edge / admin / database

In order to be stable again, we need to stop all dacha and than start them again.

Not reproduced when k8s is not overloaded (thus it should not happen)... I was waiting to have more info before creating a issue.

**Comment by rvowles** [comment] 2023-04-21 08:52
Yes, I expect that if something causes starvation it's going to be an issue. There is a PR that will let you do a full cache republish.

**Comment by rvowles** [comment] 2023-05-04 06:25
![image (6)](https://user-images.githubusercontent.com/55768/236126376-3202ad79-52b6-4d7b-8843-f286bc882fc4.png)
![image (7)](https://user-images.githubusercontent.com/55768/236126432-9c3e641d-8966-45d3-9d8f-b5cafa9d6d8d.png)
![image (8)](https://user-images.githubusercontent.com/55768/236126470-376cd944-2d44-4146-a60f-5feb6da6085a.png)
![image (9)](https://user-images.githubusercontent.com/55768/236126506-d4b588fb-9d49-4d57-9b56-6c26e217dd5e.png)

Have landed along with a diagnostic API on Dacha1 FeatureHub instances. This is in 1.6.1-RC+

**Comment by rvowles** [comment] 2023-09-25 07:04
resolved by going to Dacha2, going to close this out as there have been a bunch of improvements in Dacha2 in 1.6.3

**Closed by rvowles** 2023-09-25 07:04 UTC
